name: Java CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run tests
        run: mvn test
        continue-on-error: true

      - name: Success
        if: success()
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          curl -s -X POST https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage -d chat_id=${TELEGRAM_CHAT_ID} -d text="Все тесты пройдены успешно"

      - name: Fail
        if: failure()
        run: |
          failed_tests=$(grep -Pzo "(?s)Tests run:.*?<<< FAILURE!.*?(?=\n\n)" results.log | grep -oP "(?<=\n\s).*(?=\s+<<< FAILURE!)" | tr '\n' ', ')
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} -d text="Tests failed in repository ${{ github.repository }}. Failed tests: ${{failed_tests}}. Check details at ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
